--item 分类信息
--OPM ITEM
SELECT --T.ITEM_ID,
       T.ITEM_NO 物料编码,
       T.ITEM_DESC1 物料描述,
       T.ITEM_UM 第一单位,
       T.ITEM_UM2 第二单位,
       T.ALLOC_CLASS      分配分类集,--这个有设置为“AUTOFIFO”才能生产批自动分配配料消耗
       T.GL_CLASS         GL分类集,
			 GL.STRUCTURE_NAME GL_FL,
       GL.CATEGORY_CONCAT_SEGS 物料分类代码,
       GL.DESCRIPTION 物料分类描述,
			 
       T.INV_CLASS        库存物料分类集,
			 INV.STRUCTURE_NAME INV_FL,
       INV.CATEGORY_CONCAT_SEGS 物料分类代码,
       INV.DESCRIPTION 物料分类描述,
			 
       T.ITEMCOST_CLASS   成本分类集,
			 CB.STRUCTURE_NAME CB_FL,
       CB.CATEGORY_CONCAT_SEGS 物料分类代码,
       CB.DESCRIPTION 物料分类描述,
			 
       t.attribute1  预算项目,
       decode(T.LOT_CTL,0,'无','有') 批次控制,
       DECODE(T.SUBLOT_CTL,0,'无','有') 子批次控制
       ,DECODE(T.LOCT_CTL,0,'无','有') 地点控制
       /*,
       T.GL_CATEGORY_ID,
       T.INV_CATEGORY_ID,
       T.COST_CATEGORY_ID,
       T.CREATION_DATE,
       T.DELETE_MARK,
       T.WHSE_ITEM_ID,
       T.INACTIVE_IND     无效标记,
       T.LAST_UPDATE_DATE,
       T.LAST_UPDATED_BY,
       T.**/
  FROM IC_ITEM_MST_B T,MTL_CATEGORIES_V GL
	,MTL_CATEGORIES_V INV
	,MTL_CATEGORIES_V CB
 WHERE
/*AND T.INACTIVE_IND=0--无效标记
AND T.EXPERIMENTAL_IND ==0--"实验"
AND T.DELETE_MARK =1--标记为删除
AND T.DUALUM_IND=0--0:非双UOM;1:固定；2：默认值；3：非默认控制
AND T.NONINV_IND=0--0:库存控制；1：非库存控制
AND T.LOCT_CTL=0--0:非地点控制；1：地点控制
AND T.LOT_CTL=0--0:非批次控制；1：批次控制
AND T.LOT_INDIVISIBLE=0--0:可分割；1：不可分割
AND T.SUBLOT_CTL=0--0：非子批次控制；1：子批次控制
T.ATTRIBUTE1 --生产服务费
T.ATTRIBUTE2 --海丰科目
*/
T.GL_CATEGORY_ID=GL.CATEGORY_ID
AND  NVL(GL.DISABLE_DATE,SYSDATE+1) >= SYSDATE 

AND T.INV_CATEGORY_ID=INV.CATEGORY_ID
AND  NVL(INV.DISABLE_DATE,SYSDATE+1) >= SYSDATE

AND T.COST_CATEGORY_ID=CB.CATEGORY_ID
AND  NVL(CB.DISABLE_DATE,SYSDATE+1) >= SYSDATE

AND 
 T.ITEM_NO LIKE &ITEM_NO --'01-11-99'ITEM_DESC
 AND T.ITEM_DESC1 LIKE &ITEM_DESC
 AND T.ITEM_ID LIKE &ITEM_ID
AND T.ITEM_NO NOT LIKE '09%'
and T.INACTIVE_IND=0--无效标记
--AND T.EXPERIMENTAL_IND ==0--"实验"
AND T.DELETE_MARK =0--标记为删除
/*
AND (T.ITEM_NO LIKE '08-31%'
OR T.ITEM_NO LIKE '08-32%'
OR T.ITEM_NO LIKE '08-39%'
)*/
AND INV.CATEGORY_CONCAT_SEGS  LIKE &INV_CLASS
AND CB.CATEGORY_CONCAT_SEGS  LIKE &CB_CLASS
AND GL.CATEGORY_CONCAT_SEGS  LIKE &GL_CLASS
;
